name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv sync
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run pytest -q
      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files
