name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sync deps
        run: uv sync
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .
      - name: Tests
        run: uv run pytest -q
